services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./dispenser_backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./dispenser_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
    command: npm start -- --clear
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: 