services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./dispenser_backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./dispenser_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    image: node:20
    container_name: pill_dispenser_app-frontend-1
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: 