# Generated by Django 5.2.1 on 2025-05-24 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('pill_name', models.CharField(max_length=100)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='dispenser_backend.dispenser')),
            ],
            options={
                'ordering': ['slot_number'],
                'unique_together': {('dispenser', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time', models.TimeField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dispenser_backend.container')),
            ],
            options={
                'ordering': ['container', 'weekday', 'time'],
            },
        ),
    ]
