# Generated by Django 4.2.23 on 2025-06-10 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('pill_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['slot_number'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time', models.TimeField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dispenser_backend.container')),
            ],
            options={
                'ordering': ['container', 'weekday', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_id', models.CharField(max_length=20, unique=True)),
                ('size', models.CharField(choices=[('S', 'Small - 4 containers'), ('M', 'Medium - 6 containers'), ('L', 'Large - 10 containers')], max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='container',
            name='dispenser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='dispenser_backend.dispenser'),
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together={('dispenser', 'slot_number')},
        ),
    ]
