# Generated by Django 5.2.1 on 2025-05-24 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='serial_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispenser',
            name='size',
            field=models.CharField(choices=[('S', 'Small - 4 containers'), ('M', 'Medium - 6 containers'), ('L', 'Large - 10 containers')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
