# Generated by Django 5.2.1 on 2025-05-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='busy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isManager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workingHours',
        ),
    ]
